In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [4]:
a.ndim

1

In [6]:
b = np.array([[1,5,6,4,32,3],[3.5,6,5,4,4,65]])

In [7]:
b

array([[ 1. ,  5. ,  6. ,  4. , 32. ,  3. ],
       [ 3.5,  6. ,  5. ,  4. ,  4. , 65. ]])

In [8]:
b.shape

(2, 6)

In [9]:
# get type 
b.dtype

dtype('float64')

In [10]:
# get size
a.itemsize

4

In [11]:
a.nbytes # total size

12

In [12]:
b[1,4] # get specific element

4.0

In [13]:
b[0,:] # get specific row

array([ 1.,  5.,  6.,  4., 32.,  3.])

In [14]:
b[:,2] # get specific column

array([6., 5.])

In [15]:
b[0, 1:-1:2] # step over certain columns

array([5., 4.])